import turtle

turtle.shape("turtle")
turtle.pensize(3)
turtle.penup()
turtle.goto(-200, -50)
turtle.pendown()
turtle.begin_fill()
turtle.color("red")
turtle.circle(40, steps=3)
turtle.end_fill()

turtle.penup()
turtle.goto(-100, -50)
turtle.pendown()
turtle.begin_fill()
turtle.color("blue")
turtle.circle(40, steps=4)
turtle.end_fill()

turtle.penup()
turtle.goto(0, -50)
turtle.pendown()
turtle.begin_fill()
turtle.color("green")
turtle.circle(40, steps=5)
turtle.end_fill()

turtle.penup()
turtle.goto(100, -50)
turtle.pendown()
turtle.begin_fill()
turtle.color("yellow")
turtle.circle(40, steps=6)
turtle.end_fill()

turtle.penup()
turtle.goto(200, -50)
turtle.pendown()
turtle.begin_fill()
turtle.color("orange")
turtle.circle(40, steps=7)
turtle.end_fill()

turtle.penup()
turtle.goto(-100, 60)
turtle.pendown()
turtle.begin_fill()
turtle.color("black")
turtle.write("Colorful Shapes", font = ("Times New Roman", 20, "bold"))
turtle.end_fill()
turtle.hideturtle()


turtle.done()
